config/routes.rb
Rails.application.routes.draw do
  get 'tags/index'

  get 'menu/index'

  get 'login/index'

  post 'login/auth'

  resources :items
  resources :categories
  resources :users do
    get :editcolor, on: :member
    patch :updatecolor, on: :member
  end

  root to: 'menu#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_taggable
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.authenticate(userid, password)
  	usr = find_by(userid: userid)
  	if usr != nil && usr.password == password
  	  usr
  	else
	  return
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :check_logined
  private
  def check_logined
  	if session[:usr]
  	  begin
  	  	@usr = User.find(session[:usr])
  	  rescue ActiveRecord::RecordNotFound
  	  	reset_session
  	  end
  	end

  	unless @usr
  	  redirect_to controller: :login, action: :index
  	end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.where(user: session[:usr])
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @category.user_id = session[:usr]

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:user_id, :categoryname)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.where(user: session[:usr])
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user_id = session[:usr]

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :call, :status, :photo, :whatday, :date, :favolite, :tag_list, :user_id, :category_id)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :check_logined
  def index
    reset_session
  end

  def auth
  	usr =User.authenticate(params[:userid],params[:password])
  	if usr
  	  reset_session
  	  session[:usr] = usr.id
  	  redirect_to :root
  	else
  	  @error = 'ユーザーID/パスワードが間違っています。'
  	  render :index
  	end
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = []
    Item.where(user: session[:usr]).each do |item|
      item.tag_list.each{ |tag| @tags << tag }
    end
    @tags.uniq!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :editcolor, :update, :updatecolor, :destroy]
  skip_before_action :check_logined

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # GET /users/1/edit
  def editcolor
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to editcolor_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to editcolor_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def updatecolor
    respond_to do |format|
      if @user.update(user_params)
        usr =User.authenticate(@user.userid, @user.password)
        if usr
          reset_session
          session[:usr] = usr.id
          format.html { redirect_to :root }
        else
          @error = 'ユーザーID/パスワードが間違っています。'
          format.html { render :index }
        end
      else
        format.html { render :editcolor }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:userid, :name, :mail, :password, :color, :call)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :categoryname %><br>
    <%= f.text_field :categoryname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Categoryname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.categoryname %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Categoryname:</strong>
  <%= @category.categoryname %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :call %><br>
    <%= f.check_box :call %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :whatday %><br>
    <%= f.text_field :whatday %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :favolite %><br>
    <%= f.check_box :favolite %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.where(user: session[:usr]), :id, :categoryname %>
  </div>
  <div class="field">
    <%= f.label :tag_list %><br>
    <%= text_field_tag 'item[tag_list]', @item.tag_list.join(',') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Call</th>
      <th>Status</th>
      <th>Photo</th>
      <th>Whatday</th>
      <th>Date</th>
      <th>Favolite</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.call %></td>
        <td><%= item.status %></td>
        <td><%= item.photo %></td>
        <td><%= item.whatday %></td>
        <td><%= item.date %></td>
        <td><%= item.favolite %></td>
        <td><%= item.category_id %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Call:</strong>
  <%= @item.call %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @item.photo %>
</p>

<p>
  <strong>Whatday:</strong>
  <%= @item.whatday %>
</p>

<p>
  <strong>Date:</strong>
  <%= @item.date %>
</p>

<p>
  <strong>Favolite:</strong>
  <%= @item.favolite %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category_id %>
</p>

<p>
  <strong>Tag:</strong>
  <% @item.tag_list.each do |tag| %>
    <%= tag %>
  <% end %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Syulog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<% if session[:usr] %>
	  <div align="right"><%= session[:usr] %>さん　<%= link_to 'ログアウト', login_index_path %></div>
	  <div><%= link_to 'HOME', root_path %></div>
	<% else %>
	  <%= link_to 'ログイン画面', login_index_path %>
	<% end %>
</header>
<br />

<%= yield %>
<footer>
	<% if session[:usr] %>
	  おきに |
	  <%= link_to "アイテム", items_path %> |
	  <%= link_to "カテゴリー", categories_path %> |
	  <%= link_to "ユーザー", users_path %> |
	  <%= link_to "タグ", tags_index_path %> |
	  ほしい
	<% end %>
</footer>
</body>
</html>

app/views/login/auth.html.erb
<h1>Login#auth</h1>
<p>Find me in app/views/login/auth.html.erb</p>

app/views/login/index.html.erb
<p style="color: Red"><%= @error %></p>
<%= form_tag action: :auth do %>
	<div class="field">
		<%= label_tag :userid, 'ユーザーID' %>:<br />
		<%= text_field_tag :userid, '' %>
	</div>
	<div class="field">
		<%= label_tag :password, 'パスワード' %>:<br />
		<%= text_field_tag :password, '' %>
	</div>

	<%= submit_tag 'ログイン' %>
<% end %>
<%= link_to 'サインアップ', new_user_path %>

app/views/menu/index.html.erb
<div>１．カテゴリ登録</div>
<br />
<div>２．アイテム登録</div>
<br />
<div>３．通知～</div>
<br />

app/views/tags/index.html.erb
<h1>タグ一覧</h1>
<% @tags.each do |tag| %>
  #<%= tag %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br>
    <%= f.text_field :userid %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :call %><br>
    <%= f.number_field :call %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/editcolor.html.erb
<h1>Editing User</h1>

<%= form_for(@user, url: updatecolor_user_path(@user),html: {method: "patch"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Name</th>
      <th>Mail</th>
      <th>Password</th>
      <th>Color</th>
      <th>Call</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.userid %></td>
        <td><%= user.name %></td>
        <td><%= user.mail %></td>
        <td><%= user.password %></td>
        <td><%= user.color %></td>
        <td><%= user.call %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @user.userid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @user.mail %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Color:</strong>
  <%= @user.color %>
</p>

<p>
  <strong>Call:</strong>
  <%= @user.call %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>